# 24 — Acompanhamento prospectivo de outubro

O acompanhamento principal abrange 15 dias úteis com almoço: 05–09, 19–23 e 26–30/10. O calendário prevê recesso em 12–16/10. O pesquisador confirmou que não haverá almoço nos sábados letivos 24 e 31/10. Os dias 01 e 02 já ocorreram e ficam fora desta avaliação prospectiva.

A semana 05–09/10 mantém a emissão feita em 03/10, enviada por e-mail pelo pesquisador. As próximas emissões principais estão previstas para 16/10 e 23/10 e dependem dos quantitativos da nutricionista. Não são geradas antecipadamente com valores inventados.

A emissão mensal complementar utiliza um único histórico, disponível em 03/10, para prever os 15 dias restantes. O modelo foi desenvolvido com antecedência semanal de 3–7 dias; neste complemento a antecedência é de 2–27 dias. Comparações com a referência semanal precisam informar essa diferença. Treino permanece em 2023–2025 e o candidato combinado mantém 25%/75% e margem +10.

Reexecutar esta etapa confere hashes e atualiza a pontuação com consumos aprovados. Não refaz as previsões congeladas. Os arquivos de coleta e de entrada ficam separados das emissões.

In [1]:
from pathlib import Path
import subprocess, sys, os
ROOT=Path(r"F:\PRODUTO_MESTRADO")
env=dict(os.environ,PYTHONIOENCODING="utf-8",PYTHONDONTWRITEBYTECODE="1")
for action in ["preparar","confrontar"]:
    run=subprocess.run([sys.executable,str(ROOT/"scripts/validar_outubro_2026.py"),action],cwd=ROOT,env=env,capture_output=True,text=True,encoding="utf-8")
    print(run.stdout)
    if run.returncode: raise RuntimeError(run.stderr)

      data  plano_modelo_puro  antecedencia_dias
2026-10-05                180                  2
2026-10-06                170                  3
2026-10-07                172                  4
2026-10-08                166                  5
2026-10-09                172                  6
2026-10-19                181                 16
2026-10-20                171                 17
2026-10-21                171                 18
2026-10-22                167                 19
2026-10-23                175                 20
2026-10-26                182                 23
2026-10-27                171                 24
2026-10-28                173                 25
2026-10-29                165                 26
2026-10-30                175                 27
15 alvos mensais registrados; primeira emissão semanal preservada; próximas emissões aguardam informações.

{
  "status": "aguardando_consumos",
  "n_datas_previstas": 15,
  "n_consumos_aprovados": 0,
  "n_datas_semanal_pontuadas": 0,
  "n_datas_mensal_pontuadas": 0,
  "n_previsoes_semanais_emitidas": 5,
  "emissoes_registradas": {
    "mensal_20261003": "2026-10-03T11:24:09-03:00",
    "semanal_20261005": "2026-10-03T08:52:19-03:00"
  },
  "n_datas_sem_emissao_semanal": 10,
  "n_metricas": 0,
  "avaliacao_operacional": "Ainda não comprovada; registrar uso pela gestão e ocorrências reais",
  "mensal_vs_semanal": "Não atribuir diferenças só ao modelo: as antecedências e os históricos disponíveis diferem."
}

In [2]:
import pandas as pd
from IPython.display import display
OUT=ROOT/"resultados/validacao_outubro_2026"
display(pd.read_csv(OUT/"agenda_emissoes.csv"))
display(pd.read_csv(OUT/"emissoes/mensal_20261003/previsoes_congeladas.csv")[["data","dia_semana","plano_modelo_puro","antecedencia_dias"]])
display(pd.read_csv(OUT/"confrontos/metricas_outubro.csv"))

,emissao_planejada,dias_alvo,n_dias,situacao
0,2026-10-02,05–09/10,5,Emitida em 03/10; preservada; e-mail enviado p...
1,2026-10-09,12–16/10,0,Recesso; sem emissão de almoço
2,2026-10-16,19–23/10,5,Aguardar sexta e quantitativos da nutricionista
3,2026-10-23,26–30/10,5,Aguardar sexta e quantitativos da nutricionista

          data     dia_semana  plano_modelo_puro  antecedencia_dias
0   2026-10-05  segunda-feira                180                  2
1   2026-10-06    terça-feira                170                  3
2   2026-10-07   quarta-feira                172                  4
3   2026-10-08   quinta-feira                166                  5
4   2026-10-09    sexta-feira                172                  6
5   2026-10-19  segunda-feira                181                 16
6   2026-10-20    terça-feira                171                 17
7   2026-10-21   quarta-feira                171                 18
8   2026-10-22   quinta-feira                167                 19
9   2026-10-23    sexta-feira                175                 20
10  2026-10-26  segunda-feira                182                 23
11  2026-10-27    terça-feira                171                 24
12  2026-10-28   quarta-feira                173                 25
13  2026-10-29   quinta-feira                165                 26
14  2026-10-30    sexta-feira                175                 27

Empty DataFrame
Columns: [emissao, estrategia, coorte, n_datas, MAE_refeicoes, WAPE_pct, vies_refeicoes, excesso_potencial, deficit_potencial, dias_deficit, perda_hipotetica_2a1]
Index: []

## Recebimento de novas informações

Preencher `coleta/consumos_outubro_2026.csv` somente com consumos reais, fonte, data de recebimento e aprovação. Produção, sobras e refeições não atendidas são registros opcionais, não derivados da diferença entre previsão e consumo.

Preencher `entradas_semanais/quantitativos_institucionais_outubro.csv` com os quantitativos da nutricionista e a data/hora do documento que os informou. Nas sextas previstas, usar o comando `emitir_semana --inicio 2026-10-19` ou `emitir_semana --inicio 2026-10-26`. A rotina recusa a emissão antes da sexta, após as refeições, sem informação aprovada ou com alvos já observados.

Não alterar uma emissão após conhecer o consumo. A avaliação numérica e o relato de uso pela gestão são evidências diferentes. Registrar ocorrências de falta, pois consumo atendido pode não representar toda a demanda quando as refeições acabam.